version: '2'

services:
    php:
        build:
            context: .
            dockerfile: docker/dockerfiles/php/Dockerfile
        container_name: generator_php
        volumes:
            - ./volumes/data:/var/apps/generator/data
    nginx:
        image: nginx:1.11.8
        container_name: generator_nginx
        ports:
            - 80:80
        volumes:
            - ./docker/conf/nginx_vhost.conf:/etc/nginx/conf.d/default.conf
        volumes_from:
            - php
